# Generated by Django 3.0.6 on 2020-07-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20200618_1331'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialimage',
            name='corp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialImages', to='corporation.Corporation', verbose_name='所属企业'),
        ),
        migrations.AddField(
            model_name='materialtemp',
            name='corp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialTemps', to='corporation.Corporation', verbose_name='所属企业'),
        ),
    ]
