# Generated by Django 3.0.6 on 2020-07-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20200713_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtemp',
            name='media_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='企业微信文件标识'),
        ),
    ]
