# Generated by Django 3.0.6 on 2020-06-16 09:54

from django.db import migrations, models
import django.db.models.deletion
import workwechat_assist.corporation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('corp_id', models.CharField(max_length=32, unique=True, verbose_name='企业ID')),
                ('name', models.CharField(max_length=256, verbose_name='企业名称')),
                ('address', models.CharField(default='', max_length=256, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='联系电话')),
                ('industry_type', models.CharField(max_length=128, verbose_name='行业类型')),
                ('staff_size', models.CharField(default='1-50人', max_length=32, verbose_name='人员规模')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
                'db_table': 'Corporation',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_id', models.PositiveIntegerField(verbose_name='企业微信部门ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门名称')),
                ('name_en', models.CharField(blank=True, max_length=32, verbose_name='部门英文名称')),
                ('order', models.PositiveIntegerField(verbose_name='在父部门中的次序')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='corporation.Corporation', verbose_name='所属企业')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='corporation.Department', verbose_name='父部门')),
            ],
            options={
                'verbose_name': '部门信息',
                'verbose_name_plural': '部门信息',
                'db_table': 'Department',
                'unique_together': {('corp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentMemberRelationShip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(verbose_name='在部门中的次序')),
                ('is_leader_in_dept', models.BooleanField(default=False, verbose_name='部门领导')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmrels', to='corporation.Department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=64, verbose_name='成员ID')),
                ('name', models.CharField(max_length=64, verbose_name='成员名称')),
                ('alias', models.CharField(blank=True, max_length=32, verbose_name='成员别名')),
                ('mobile', models.CharField(blank=True, max_length=16, verbose_name='手机号码')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='地址')),
                ('position', models.CharField(blank=True, max_length=128, verbose_name='职务')),
                ('external_position', models.CharField(blank=True, max_length=128, verbose_name='对外职务')),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female')], default='1', max_length=2, verbose_name='性别')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('telephone', models.CharField(blank=True, max_length=32, verbose_name='座机')),
                ('avatar_mediaid', models.CharField(blank=True, max_length=64, verbose_name='成员头像mediaid')),
                ('enable', models.BooleanField(default=True, verbose_name='启用成员')),
                ('to_invite', models.BooleanField(default=True, verbose_name='邀请使用企业微信')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='corporation.Corporation', verbose_name='所属企业')),
                ('departments', models.ManyToManyField(through='corporation.DepartmentMemberRelationShip', to='corporation.Department')),
            ],
            options={
                'verbose_name': '成员信息',
                'verbose_name_plural': '成员信息',
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='ExternalAttr',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(0, '文本'), (1, '网页'), (2, '小程序')], default=0, verbose_name='类型')),
                ('name', models.CharField(max_length=64, verbose_name='属性名称')),
                ('value', models.CharField(blank=True, max_length=64, null=True, verbose_name='文本属性值')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网页URL')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='标题')),
                ('appid', models.CharField(max_length=64, verbose_name='小程序appid')),
                ('pagepath', models.CharField(max_length=64, verbose_name='小程序页面路径')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalAttrs', to='corporation.Corporation', verbose_name='所属企业')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalAttrs', to='corporation.Member', verbose_name='成员对外信息')),
            ],
            options={
                'verbose_name': '成员对外属性',
                'verbose_name_plural': '成员对外属性',
                'db_table': 'ExternalAttr',
            },
        ),
        migrations.AddField(
            model_name='departmentmemberrelationship',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmrels', to='corporation.Member', verbose_name='成员'),
        ),
        migrations.CreateModel(
            name='CorpApp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='盘陀企业微信助手', max_length=128, verbose_name='APP名称')),
                ('agent_id', models.CharField(max_length=32, verbose_name='企业微信回调应用ID')),
                ('secret', models.CharField(max_length=64, verbose_name='企业微信应用加密密钥')),
                ('token', models.CharField(max_length=32, verbose_name='企业微信回调Token')),
                ('aes_key', models.CharField(max_length=64, verbose_name='企业微信回调EncodingAESKey')),
                ('access_token', models.CharField(blank=True, max_length=64, verbose_name='访问票据')),
                ('token_valid_time', models.DateTimeField(default=workwechat_assist.corporation.models.one_hour_later, null=True, verbose_name='票据有效时间')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='corporation.Corporation', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '企业微信应用信息',
                'verbose_name_plural': '企业微信应用信息',
                'db_table': 'CorpApp',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='员工标签')),
                ('tag_id', models.PositiveIntegerField(verbose_name='企业微信Tag ID')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='corporation.Corporation', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '员工标签信息',
                'verbose_name_plural': '员工标签信息',
                'db_table': 'Tag',
                'unique_together': {('corp', 'name')},
            },
        ),
    ]
