# Generated by Django 3.0.6 on 2020-06-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpapp',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='corpapp',
            name='token_valid_time',
        ),
        migrations.AlterField(
            model_name='corporation',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='地址'),
        ),
    ]
