# Generated by Django 3.0.6 on 2020-06-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0002_auto_20200617_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpapp',
            name='aes_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='企业微信回调EncodingAESKey'),
        ),
        migrations.AlterField(
            model_name='corpapp',
            name='agent_id',
            field=models.CharField(max_length=32, verbose_name='企业微信AgentId'),
        ),
        migrations.AlterField(
            model_name='corpapp',
            name='secret',
            field=models.CharField(max_length=64, verbose_name='企业微信Secret'),
        ),
        migrations.AlterField(
            model_name='corpapp',
            name='token',
            field=models.CharField(blank=True, max_length=32, verbose_name='企业微信回调Token'),
        ),
    ]
