# Generated by Django 3.0.6 on 2020-06-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0005_auto_20200617_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.PositiveIntegerField(null=True, verbose_name='企业微信部门ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(null=True, verbose_name='在父部门中的次序'),
        ),
    ]
