# Generated by Django 3.0.6 on 2020-06-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0006_auto_20200617_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpapp',
            name='agent_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='企业微信AgentId'),
        ),
    ]
