# Generated by Django 3.0.6 on 2020-06-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0007_auto_20200617_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corpapp',
            unique_together={('corp', 'name')},
        ),
    ]
