# Generated by Django 3.0.6 on 2020-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0009_auto_20200617_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='avatar_mediaid',
        ),
        migrations.RemoveField(
            model_name='member',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='member',
            name='to_invite',
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.URLField(blank=True, verbose_name='成员头像'),
        ),
        migrations.AddField(
            model_name='member',
            name='open_userid',
            field=models.CharField(blank=True, default=True, max_length=64, verbose_name='成员OpenID'),
        ),
        migrations.AddField(
            model_name='member',
            name='qr_code',
            field=models.URLField(blank=True, verbose_name='个人二维码'),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'FORBIDDEN'), (4, 'INACTIVE'), (5, 'QUIT')], default=1, verbose_name='激活状态'),
        ),
        migrations.AddField(
            model_name='member',
            name='thumb_avatar',
            field=models.URLField(blank=True, verbose_name='头像缩略图'),
        ),
    ]
