# Generated by Django 3.0.6 on 2020-06-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0010_auto_20200617_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmemberrelationship',
            options={'verbose_name': '成员部门绑定信息', 'verbose_name_plural': '成员部门绑定信息'},
        ),
        migrations.AlterModelTable(
            name='departmentmemberrelationship',
            table='DepartmentMemberRelationShip',
        ),
    ]
