# Generated by Django 3.0.6 on 2020-06-17 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0011_auto_20200617_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='启用成员'),
        ),
    ]
