# Generated by Django 3.0.6 on 2020-06-18 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0013_auto_20200617_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tagid',
            field=models.PositiveIntegerField(default=1, verbose_name='标签ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tagname',
            field=models.CharField(default='', max_length=32, verbose_name='标签名称'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('corp', 'userid')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('corp', 'tagname')},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_id',
        ),
    ]
