# Generated by Django 3.0.6 on 2020-06-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0015_auto_20200618_0914'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='MemberTag',
        ),
    ]
