# Generated by Django 3.0.6 on 2020-07-17 08:44

from django.db import migrations, models
import workwechat_assist.corporation.models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20200618_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='naruto',
            field=models.CharField(blank=True, default=workwechat_assist.corporation.models.gen_naruto, max_length=64, null=True, verbose_name='Naruto'),
        ),
    ]
