# Generated by Django 3.0.6 on 2020-07-17 08:53

from django.db import migrations, models
import workwechat_assist.corporation.models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0017_member_naruto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='naruto',
            field=models.CharField(default=workwechat_assist.corporation.models.gen_naruto, max_length=64, unique=True, verbose_name='Naruto'),
        ),
    ]
