# Generated by Django 3.0.6 on 2020-06-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProfile/avatar/%y/%d/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatarUrl',
            field=models.URLField(blank=True, default='', max_length=256, verbose_name='微信头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default='0', max_length=4, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickName',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='微信昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='微信openid'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', '管理员'), ('M', '经理'), ('DM', '部门经理'), ('E', '员工')], default='E', max_length=4, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='微信UnionID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
