# Generated by Django 3.0.6 on 2020-06-18 05:31

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporation', '0016_auto_20200618_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_userid', models.CharField(max_length=64, verbose_name='客户userid')),
                ('name', models.CharField(max_length=64, verbose_name='客户名称')),
                ('avatar', models.URLField(blank=True, verbose_name='成员头像')),
                ('type', models.SmallIntegerField(choices=[(1, 'wechat'), (2, 'work_wechat')], default=1, verbose_name='激活状态')),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female')], default='1', max_length=2, verbose_name='性别')),
                ('unionid', models.CharField(blank=True, default='', max_length=32, verbose_name='微信unionid')),
                ('position', models.CharField(blank=True, default='', max_length=32, verbose_name='职位')),
                ('corp_name', models.CharField(blank=True, default='', max_length=32, verbose_name='企业简称')),
                ('corp_full_name', models.CharField(blank=True, default='', max_length=32, verbose_name='企业全称')),
                ('external_profile', jsonfield.fields.JSONField(null=True, verbose_name='自定义展示信息')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='corporation.Corporation', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=32, verbose_name='标签组名称')),
                ('groupid', models.CharField(blank=True, max_length=64, verbose_name='标签组ID')),
                ('create_time', models.PositiveIntegerField(null=True, verbose_name='创建时间')),
                ('order', models.PositiveIntegerField(null=True, verbose_name='次序值')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggroups', to='corporation.Corporation', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '客户标签组',
                'verbose_name_plural': '客户标签组',
                'db_table': 'TagGroup',
                'unique_together': {('corp', 'groupname')},
            },
        ),
        migrations.CreateModel(
            name='CustomerFollowUserRelationship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(blank=True, default='', max_length=32, verbose_name='备注')),
                ('description', models.CharField(blank=True, default='', max_length=32, verbose_name='描述')),
                ('remark_corp_name', models.CharField(blank=True, default='', max_length=32, verbose_name='备注企业')),
                ('createtime', models.PositiveIntegerField(null=True, verbose_name='添加联系人时间')),
                ('tags', jsonfield.fields.JSONField(null=True, verbose_name='客户标签')),
                ('remark_mobiles', models.CharField(blank=True, default='', max_length=32, verbose_name='备注手机号码')),
                ('add_way', models.SmallIntegerField(default=3, verbose_name='客户来源')),
                ('state', models.CharField(blank=True, max_length=64, verbose_name='自定义来源')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfuRels', to='externalcontact.Customer', verbose_name='客户')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfuRels', to='corporation.Member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '客户与成员绑定信息',
                'verbose_name_plural': '客户与成员绑定信息',
                'db_table': 'CustomerFollowUserRelationship',
                'unique_together': {('member', 'customer')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='member',
            field=models.ManyToManyField(through='externalcontact.CustomerFollowUserRelationship', to='corporation.Member'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tagname', models.CharField(max_length=32, verbose_name='标签名称')),
                ('tagid', models.CharField(blank=True, max_length=64, verbose_name='标签ID')),
                ('create_time', models.PositiveIntegerField(null=True, verbose_name='创建时间')),
                ('order', models.PositiveIntegerField(null=True, verbose_name='次序值')),
                ('taggroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='externalcontact.TagGroup', verbose_name='标签组')),
            ],
            options={
                'verbose_name': '客户标签组',
                'verbose_name_plural': '客户标签组',
                'db_table': 'CustomerTag',
                'unique_together': {('taggroup', 'tagname')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('corp', 'external_userid')},
        ),
    ]
