# Generated by Django 3.0.6 on 2020-06-18 05:49

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20200618_1331'),
        ('externalcontact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='群名')),
                ('chat_id', models.CharField(blank=True, max_length=64, verbose_name='群ID')),
                ('owner', models.CharField(blank=True, max_length=64, verbose_name='群主ID')),
                ('create_time', models.PositiveIntegerField(null=True, verbose_name='创建时间')),
                ('notice', models.CharField(blank=True, max_length=64, verbose_name='群公告')),
                ('members', jsonfield.fields.JSONField(null=True, verbose_name='群成员')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupchats', to='corporation.Corporation', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '客户群',
                'verbose_name_plural': '客户群',
                'db_table': 'GroupChat',
                'unique_together': {('corp', 'name')},
            },
        ),
    ]
