# Generated by Django 3.0.6 on 2020-06-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontact', '0002_groupchat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '客户标签', 'verbose_name_plural': '客户标签'},
        ),
    ]
