# Generated by Django 3.0.6 on 2020-06-18 08:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontact', '0003_auto_20200618_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='external_profile',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='自定义展示信息'),
        ),
        migrations.AlterUniqueTogether(
            name='customerfollowuserrelationship',
            unique_together=set(),
        ),
    ]
