# Generated by Django 3.0.6 on 2020-06-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20200618_1331'),
        ('externalcontact', '0004_auto_20200618_1606'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerfollowuserrelationship',
            unique_together={('member', 'customer')},
        ),
    ]
