# Generated by Django 3.0.6 on 2020-06-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontact', '0006_auto_20200618_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='taggroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='externalcontact.TagGroup', verbose_name='标签组'),
        ),
    ]
