# Generated by Django 3.0.6 on 2020-06-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontact', '0007_auto_20200618_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='taggroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='externalcontact.TagGroup', verbose_name='标签组'),
        ),
    ]
