# Generated by Django 3.0.6 on 2020-06-21 02:20

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20200618_1331'),
        ('externalcontact', '0008_auto_20200621_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='chat_id',
            field=models.CharField(max_length=64, verbose_name='群ID'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='群成员'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='群名'),
        ),
        migrations.AlterUniqueTogether(
            name='groupchat',
            unique_together={('corp', 'chat_id')},
        ),
    ]
