# Generated by Django 3.0.6 on 2020-06-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontact', '0009_auto_20200621_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '跟进人离职'), (2, '离职继承中'), (3, '离职继承完成')], default=0, verbose_name='客户群状态'),
        ),
    ]
