# Generated by Django 3.0.6 on 2020-06-21 03:56

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20200618_1331'),
        ('externalcontact', '0010_groupchat_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('msg_id', models.CharField(max_length=64, verbose_name='群发消息ID')),
                ('content', jsonfield.fields.JSONField(null=True, verbose_name='消息内容')),
                ('detail_list', jsonfield.fields.JSONField(null=True, verbose_name='群发消息发送结果')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmessages', to='corporation.Corporation', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '群发消息',
                'verbose_name_plural': '群发消息',
                'db_table': 'GroupMessage',
                'unique_together': {('corp', 'msg_id')},
            },
        ),
    ]
