# Generated by Django 3.0.6 on 2020-06-21 04:45

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20200618_1331'),
        ('externalcontact', '0011_groupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('config_id', models.CharField(max_length=64, verbose_name='联系我配置Id')),
                ('type', models.SmallIntegerField(choices=[(1, '单人'), (2, '多人')], default=1, verbose_name='联系方式类型')),
                ('scene', models.SmallIntegerField(choices=[(1, '小程序联系'), (2, '二维码联系')], default=2, verbose_name='场景')),
                ('style', models.SmallIntegerField(default=1, null=True, verbose_name='小程序中的控件样式')),
                ('remark', models.CharField(blank=True, max_length=32, verbose_name='备注信息')),
                ('skip_verify', models.BooleanField(default=True, verbose_name='是否无需验证')),
                ('qr_code', models.URLField(blank=True, null=True, verbose_name='联系二维码的URL')),
                ('state', models.CharField(blank=True, max_length=32, verbose_name='添加渠道')),
                ('user', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='成员userId列表')),
                ('party', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='部门id列表')),
                ('is_temp', jsonfield.fields.JSONField(default=False, verbose_name='是否临时会话')),
                ('expires_in', models.PositiveIntegerField(default=604800, verbose_name='临时会话二维码有效期')),
                ('chat_expires_in', models.PositiveIntegerField(default=86400, verbose_name='临时会话有效期')),
                ('unionid', models.CharField(blank=True, max_length=64, verbose_name='客户unionid')),
                ('conclusions', jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='结束语')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactmes', to='corporation.Corporation', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '联系我信息',
                'verbose_name_plural': '联系我信息',
                'db_table': 'ContactMe',
                'unique_together': {('corp', 'config_id')},
            },
        ),
    ]
