# Generated by Django 3.0.6 on 2020-06-21 04:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontact', '0012_contactme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='chat_expires_in',
            field=models.PositiveIntegerField(default=86400, null=True, verbose_name='临时会话有效期'),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='expires_in',
            field=models.PositiveIntegerField(default=604800, null=True, verbose_name='临时会话二维码有效期'),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='is_temp',
            field=jsonfield.fields.JSONField(default=False, null=True, verbose_name='是否临时会话'),
        ),
    ]
