# Generated by Django 3.0.6 on 2020-06-28 08:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontact', '0014_auto_20200621_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='tags',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='应用标签'),
        ),
        migrations.AddField(
            model_name='contactme',
            name='welcome_code',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='欢迎语'),
        ),
    ]
