# Generated by Django 3.0.6 on 2020-06-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontact', '0016_auto_20200628_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='客户流失'),
        ),
    ]
