# Generated by Django 3.0.6 on 2020-06-30 07:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontact', '0017_contactme_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='member',
            new_name='members',
        ),
        migrations.AlterField(
            model_name='customerfollowuserrelationship',
            name='remark_mobiles',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='备注手机号码'),
        ),
    ]
