# Generated by Django 3.0.6 on 2020-07-16 07:34

from django.db import migrations, models
import workwechat_assist.moment.models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=workwechat_assist.moment.models.user_directory_path, verbose_name='视频'),
        ),
    ]
